#!/usr/bin/env bash
#Installing nginx on your web-01 server
#Nginx listens on port 80
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-githu.html
service nginx restart
