#!/usr/bin/env bash
#Configuring Nginx server to/redirect_me is redirecting to another page.
STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/8HaTRLzcUIU?si=--IvsE-SgdfWB5QB; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-githu.html
sed -i "37i\ $REDIRECT" "$FILE"
service nginx restart
