#!/usr/bin/env bash
# installing the load balancer


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 314601-web-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 314601-web-02 54.89.182.66 check\n\tserver 314601-lb-01 54.87.251.70 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
